name: PR

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  PR:
    runs-on: ubuntu-latest
    outputs:
        requires-visual: ${{ steps['visual_tests_check'].outputs['requires_visual_tests'] }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            examples:
              - examples/**
            components:
              - packages/**
              - '!packages/**/*-test.js'
              - '!packages/**/*-test.tsx'
              - '!packages/**/*.md'
              - '!packages/*.md'

      - name: Record file check output
      # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
        id: visual_tests_check
        run: requires_visual_tests=${{ steps.changed-files.outputs.examples_any_changed == 'true' || steps.changed-files.outputs.components_any_changed == 'true'}}
#        if: steps.changed-files.outputs.examples_any_changed == 'true' || steps.changed-files.outputs.components_any_changed == 'true'
#        env:
#          EXAMPLES_ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.examples_all_changed_files }}
#          COMPONENTS_ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.components_all_changed_files }}
#        run: |
#          echo "One or more test file(s) has changed."
#          echo $EXAMPLES_ALL_CHANGED_FILES
#          echo $COMPONENTS_ALL_CHANGED_FILES

#  echo "List all the files that have changed: $EXAMPLES_ALL_CHANGED_FILES"

#      - name: Run step if component file(s) change
#      # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
#        if: steps.changed-files.outputs.components_any_changed == 'true'
#        env:
#          COMPONENTS_ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.components_all_changed_files }}
#        run: |
#          echo "One or more test file(s) has changed."
#          echo "List all the files that have changed: $COMPONENTS_ALL_CHANGED_FILES"

      - name: Force percy/backpack to succeed
        # Only run on pull_requests and when specific changes to files have occurred.
        if: ${{ github.event_name == 'pull_request' && steps.changed-files.outputs.examples_any_changed != 'true' || steps.changed-files.outputs.components_any_changed != 'true' }}
        run: |
          curl --request POST \
          --url https://github.com/api/v3/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "success",
            "description": "No files requiring visual tests detected. Automatically passing Percy.",
            "context": "percy/backpack",
            "target_url": "${{ github.event.workflow_run.html_url }}"
            }' \
          --fail

  PercyTests:
    if: (needs.visual-files-changed.outputs.requires-visual == 'true')
    runs-on: ubuntu-latest
    needs: PR
    permissions:
      statuses: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Running
        run: echo "I have run"

