name: PR

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Create build
        run: npm run build

#      - name: Get changed files
#        id: changed-files
#        uses: tj-actions/changed-files@v44.4.0
#          # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
#          # with:
#          #   since_last_remote_commit: true
#
#      - name: List all changed files
#        env:
#          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
#        run: |
#          for file in ${ALL_CHANGED_FILES}; do
#            echo "$file was changed"
#          done

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: 'true'
          files_yaml: |
            examples:
              - examples/**
            components:
              - packages/**
              - '!packages/**/*-test.js'
              - '!packages/**/*-test.tsx'
              - '!packages/**/*.md'
              - '!packages/*.md'

      - name: Run step if examples file(s) change
      # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
        if: steps.changed-files.outputs.examples_any_changed == 'true'
        env:
          EXAMPLES_ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.examples_all_changed_files }}
        run: |
          echo "One or more test file(s) has changed."
          echo "List all the files that have changed: $EXAMPLES_ALL_CHANGED_FILES"

      - name: Run step if component file(s) change
      # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
        if: steps.changed-files.outputs.components_any_changed == 'true'
        env:
          COMPONENTS_ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.components_all_changed_files }}
        run: |
          echo "One or more test file(s) has changed."
          echo "List all the files that have changed: $COMPONENTS_ALL_CHANGED_FILES"
